name: Add build.sh to All Branches

on:
  workflow_dispatch:
    inputs:
      continue:
        description: 'Do you want to continue?'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

jobs:
  add-build-sh:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.continue == 'yes' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get all branches
      id: get-branches
      run: |
        branches=$(git for-each-ref --format='%(refname:short)' refs/heads/)
        echo "branches=$branches" >> $GITHUB_ENV
        echo "::set-output name=branches::${branches}"

    - name: Display branches
      run: |
        echo "Branches: ${{ env.branches }}"

    - name: Add build.sh to all branches
      run: |
        FILE_TO_ADD="build.sh"
        COMMIT_MESSAGE="Add build.sh to all branches"
        
        for branch in ${{ steps.get-branches.outputs.branches }}; do
          git checkout $branch
          cp $GITHUB_WORKSPACE/$FILE_TO_ADD .
          git add $FILE_TO_ADD
          git commit -m "$COMMIT_MESSAGE"
          git push origin $branch
        done
